
import { AsmaulHusna } from './types';

export const ASMA_UL_HUSNA: AsmaulHusna[] = [
  { name: "ٱلْرَّحْمَـانُ", transliteration: "Ar-Rahman", meaning: "The Beneficent" },
  { name: "ٱلْرَّحِيْمُ", transliteration: "Ar-Rahim", meaning: "The Merciful" },
  { name: "ٱلْمَلِكُ", transliteration: "Al-Malik", meaning: "The King" },
  { name: "ٱلْقُدُّوسُ", transliteration: "Al-Quddus", meaning: "The Most Holy" },
  { name: "ٱلْسَّلَامُ", transliteration: "As-Salam", meaning: "The Source of Peace" },
  { name: "ٱلْمُؤْمِنُ", transliteration: "Al-Mu'min", meaning: "The Guardian of Faith" },
  { name: "ٱلْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meaning: "The Protector" },
  { name: "ٱلْعَزِيزُ", transliteration: "Al-Aziz", meaning: "The Mighty" },
  { name: "ٱلْجَبَّارُ", transliteration: "Al-Jabbar", meaning: "The Compeller" },
  { name: "ٱلْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meaning: "The Majestic" },
  { name: "ٱلْخَالِقُ", transliteration: "Al-Khaliq", meaning: "The Creator" },
  { name: "ٱلْبَارِئُ", transliteration: "Al-Bari'", meaning: "The Evolver" },
  { name: "ٱلْمُصَوِّرُ", transliteration: "Al-Musawwir", meaning: "The Fashioner" },
  { name: "ٱلْغَفَّارُ", transliteration: "Al-Ghaffar", meaning: "The Great Forgiver" },
  { name: "ٱلْقَهَّارُ", transliteration: "Al-Qahhar", meaning: "The Subduer" },
  { name: "ٱلْوَهَّابُ", transliteration: "Al-Wahhab", meaning: "The Bestower" },
  { name: "ٱلْرَّزَّاقُ", transliteration: "Ar-Razzaq", meaning: "The Sustainer" },
  { name: "ٱلْفَتَّاحُ", transliteration: "Al-Fattah", meaning: "The Opener" },
  { name: "ٱلْعَلِيمُ", transliteration: "Al-Alim", meaning: "The All-Knowing" },
  { name: "ٱلْقَابِضُ", transliteration: "Al-Qabid", meaning: "The Withholder" },
  { name: "ٱلْبَاسِطُ", transliteration: "Al-Basit", meaning: "The Expander" },
  { name: "ٱلْخَافِضُ", transliteration: "Al-Khafid", meaning: "The Humbler" },
  { name: "ٱلْرَّافِعُ", transliteration: "Ar-Rafi'", meaning: "The Exalter" },
  { name: "ٱلْمُعِزُّ", transliteration: "Al-Mu'izz", meaning: "The Honorer" },
  { name: "ٱلْمُذِلُّ", transliteration: "Al-Mudhill", meaning: "The Dishonorer" },
  { name: "ٱلْسَّمِيعُ", transliteration: "As-Sami'", meaning: "The All-Hearing" },
  { name: "ٱلْبَصِيرُ", transliteration: "Al-Basir", meaning: "The All-Seeing" },
  { name: "ٱلْحَكَمُ", transliteration: "Al-Hakam", meaning: "The Judge" },
  { name: "ٱلْعَدْلُ", transliteration: "Al-Adl", meaning: "The Just" },
  { name: "ٱلْلَّطِيفُ", transliteration: "Al-Latif", meaning: "The Subtle One" },
  { name: "ٱلْخَبِيرُ", transliteration: "Al-Khabir", meaning: "The All-Aware" },
  { name: "ٱلْحَلِيمُ", transliteration: "Al-Halim", meaning: "The Forbearing" },
  { name: "ٱلْعَظِيمُ", transliteration: "Al-Azim", meaning: "The Magnificent" },
  { name: "ٱلْغَفُورُ", transliteration: "Al-Ghafur", meaning: "The Forgiving" },
  { name: "ٱلْشَّكُورُ", transliteration: "Ash-Shakur", meaning: "The Appreciative" },
  { name: "ٱلْعَلِيُّ", transliteration: "Al-Ali", meaning: "The Most High" },
  { name: "ٱلْكَبِيرُ", transliteration: "Al-Kabir", meaning: "The Great" },
  { name: "ٱلْحَفِيظُ", transliteration: "Al-Hafiz", meaning: "The Preserver" },
  { name: "ٱلْمُقِيتُ", transliteration: "Al-Muqit", meaning: "The Nourisher" },
  { name: "ٱلْحَسِيبُ", transliteration: "Al-Hasib", meaning: "The Reckoner" },
  { name: "ٱلْجَلِيلُ", transliteration: "Al-Jalil", meaning: "The Sublime One" },
  { name: "ٱلْكَرِيمُ", transliteration: "Al-Karim", meaning: "The Generous" },
  { name: "ٱلْرَّقِيبُ", transliteration: "Ar-Raqib", meaning: "The Watchful" },
  { name: "ٱلْمُجِيبُ", transliteration: "Al-Mujib", meaning: "The Responsive" },
  { name: "ٱلْوَاسِعُ", transliteration: "Al-Wasi'", meaning: "The All-Encompassing" },
  { name: "ٱلْحَكِيمُ", transliteration: "Al-Hakim", meaning: "The Wise" },
  { name: "ٱلْوَدُودُ", transliteration: "Al-Wadud", meaning: "The Loving" },
  { name: "ٱلْمَجِيدُ", transliteration: "Al-Majid", meaning: "The Glorious" },
  { name: "ٱلْبَاعِثُ", transliteration: "Al-Ba'ith", meaning: "The Resurrector" },
  { name: "ٱلْشَّهِيدُ", transliteration: "Ash-Shahid", meaning: "The Witness" },
  { name: "ٱلْحَقُّ", transliteration: "Al-Haqq", meaning: "The Truth" },
  { name: "ٱلْوَكِيلُ", transliteration: "Al-Wakil", meaning: "The Trustee" },
  { name: "ٱلْقَوِيُّ", transliteration: "Al-Qawiyy", meaning: "The Strong" },
  { name: "ٱلْمَتِينُ", transliteration: "Al-Matin", meaning: "The Firm One" },
  { name: "ٱلْوَلِيُّ", transliteration: "Al-Waliyy", meaning: "The Protecting Friend" },
  { name: "ٱلْحَمِيدُ", transliteration: "Al-Hamid", meaning: "The Praiseworthy" },
  { name: "ٱلْمُحْصِيُ", transliteration: "Al-Muhsi", meaning: "The Accounter" },
  { name: "ٱلْمُبْدِئُ", transliteration: "Al-Mubdi'", meaning: "The Originator" },
  { name: "ٱلْمُعِيدُ", transliteration: "Al-Mu'id", meaning: "The Restorer" },
  { name: "ٱلْمُحْيِى", transliteration: "Al-Muhyi", meaning: "The Giver of Life" },
  { name: "ٱلْمُمِيتُ", transliteration: "Al-Mumit", meaning: "The Taker of Life" },
  { name: "ٱلْحَىُّ", transliteration: "Al-Hayy", meaning: "The Ever-Living" },
  { name: "ٱلْقَيُّومُ", transliteration: "Al-Qayyum", meaning: "The Self-Subsisting" },
  { name: "ٱلْوَاجِدُ", transliteration: "Al-Wajid", meaning: "The Perceiver" },
  { name: "ٱلْمَاجِدُ", transliteration: "Al-Majid", meaning: "The Illustrious" },
  { name: "ٱلْوَاحِدُ", transliteration: "Al-Wahid", meaning: "The One" },
  { name: "ٱلْأَحَدُ", transliteration: "Al-Ahad", meaning: "The Unique" },
  { name: "ٱلْصَّمَدُ", transliteration: "As-Samad", meaning: "The Eternal" },
  { name: "ٱلْقَادِرُ", transliteration: "Al-Qadir", meaning: "The Able" },
  { name: "ٱلْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meaning: "The Powerful" },
  { name: "ٱلْمُقَدِّمُ", transliteration: "Al-Muqaddim", meaning: "The Expediter" },
  { name: "ٱلْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meaning: "The Delayer" },
  { name: "ٱلْأَوَّلُ", transliteration: "Al-Awwal", meaning: "The First" },
  { name: "ٱلْآخِرُ", transliteration: "Al-Akhir", meaning: "The Last" },
  { name: "ٱلْظَّاهِرُ", transliteration: "Az-Zahir", meaning: "The Manifest" },
  { name: "ٱلْبَاطِنُ", transliteration: "Al-Batin", meaning: "The Hidden" },
  { name: "ٱلْوَالِي", transliteration: "Al-Wali", meaning: "The Governor" },
  { name: "ٱلْمُتَعَالِي", transliteration: "Al-Muta'ali", meaning: "The Most Exalted" },
  { name: "ٱلْبَرُّ", transliteration: "Al-Barr", meaning: "The Source of All Goodness" },
  { name: "ٱلْتَّوَّابُ", transliteration: "At-Tawwab", meaning: "The Acceptor of Repentance" },
  { name: "ٱلْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meaning: "The Avenger" },
  { name: "ٱلْعَفُوُّ", transliteration: "Al-Afuww", meaning: "The Pardoner" },
  { name: "ٱلْرَّؤُوفُ", transliteration: "Ar-Ra'uf", meaning: "The Compassionate" },
  { name: "مَالِكُ ٱلْمُلْكُ", transliteration: "Malik-ul-Mulk", meaning: "The Owner of All Sovereignty" },
  { name: "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامُ", transliteration: "Dhul-Jalali wal-Ikram", meaning: "The Lord of Majesty and Bounty" },
  { name: "ٱلْمُقْسِطُ", transliteration: "Al-Muqsit", meaning: "The Equitable" },
  { name: "ٱلْجَامِعُ", transliteration: "Al-Jami'", meaning: "The Gatherer" },
  { name: "ٱلْغَنِيُّ", transliteration: "Al-Ghani", meaning: "The Self-Sufficient" },
  { name: "ٱلْمُغْنِيُّ", transliteration: "Al-Mughni", meaning: "The Enricher" },
  { name: "ٱلْمَانِعُ", transliteration: "Al-Mani'", meaning: "The Preventer" },
  { name: "ٱلْضَّارُ", transliteration: "Ad-Darr", meaning: "The Distresser" },
  { name: "ٱلْنَّافِعُ", transliteration: "An-Nafi'", meaning: "The Propitious" },
  { name: "ٱلْنُّورُ", transliteration: "An-Nur", meaning: "The Light" },
  { name: "ٱلْهَادِي", transliteration: "Al-Hadi", meaning: "The Guide" },
  { name: "ٱلْبَدِيعُ", transliteration: "Al-Badi'", meaning: "The Incomparable" },
  { name: "ٱلْبَاقِي", transliteration: "Al-Baqi", meaning: "The Everlasting" },
  { name: "ٱلْوَارِثُ", transliteration: "Al-Warith", meaning: "The Supreme Inheritor" },
  { name: "ٱلْرَّشِيدُ", transliteration: "Ar-Rashid", meaning: "The Guide to the Right Path" },
  { name: "ٱلْصَّبُورُ", transliteration: "As-Sabur", meaning: "The Patient" },
];
